ministryofjustice/hmpps-incident-reporting

feature.env, integration_tests/e2e/signIn.cy.ts, integration_tests/mockApis/frontendComponents.ts, integration_tests/pages/page.ts, server/data/frontendComponentsClient.ts, server/data/index.ts, server/middleware/setUpWebSecurity.ts, server/services/index.ts, server/utils/nunjucksSetup.ts
Previously, stubbing did not work for DPS’ frontend components api as the url was never set to point to wiremock.
Now, in most tests the fallback header and footer is used (to make signing in possible) but a new test exists to ensure html, css and javascript is correctly loaded.
=> IR-68: Improve integration tests

.eslintrc.json, helm_deploy/hmpps-incident-reporting/values.yaml, package-lock.json, package.json, server/config.ts, server/data/hmppsAuditClient.test.ts, server/data/hmppsAuditClient.ts, server/services/auditService.test.ts, server/services/auditService.ts
Copied from [upstream template](https://github.com/ministryofjustice/hmpps-template-typescript/pull/327) but the audit client is _not_ provided to the app’s “services”
=> Add (disabled) audit client (hmpps-template-typescript#327)

.circleci/config.yml
Ref [api#107](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/107)
=> IR-68: Use latest LTS java for Veracode scanning

server/utils/nunjucksSetup.ts
The app runs from within the `/dist` folder into which assets are built along with the *manifest* file. This manifest file is used from within nunjucks templates to map local paths to versioned assets.
However, tests run from the actual sources and cannot find the manifest file, leading to a wall of inconsequential error messages.
For now it’s easiest to silence this error in test mode. `jest` tests don’t actually even try to load any assets; there is no server running.
Once the template project decides on a better workaround, we can cherry-pick it and remove this solution.
=> IR-68: Silence asset manifest file error during tests

.circleci/config.yml, integration_tests/tsconfig.json
• `eslint` already ran in CircleCI build job but for some reason `tsc` did not
• integration tests now compile to a more-modern version of javascript
=> IR-68: Run type-checking in CircleCI

server/@types/index.d.ts, server/config.ts, server/data/incidentReportingApi.ts, server/data/incidentReportingApiUtils.ts, server/routes/index.ts, server/utils/utils.test.ts, server/utils/utils.ts, server/views/pages/events.njk
Added a basic client to talk with the [Incident Reporting API](https://incident-reporting-api-dev.hmpps.service.justice.gov.uk/swagger-ui/index.html#/).
- wiring to read client settings (URL, etc...)
- TS types
- methods to get list of incidents "events" and reports
- with filtering/pagination/sorting
- methods to get single incident "event" and single basic report, by ID or reference 
- conversion of JSON datetimes from strings to JS `Date`
The API has many more endpoints that are currently not exposed in this client.
However this is a minimal set of features that can be merged and potentially used by others in the team to start to build some basic pages to display lists events/reports or single events/reports without additional details.
I plan to add at least more methods for the …
=> IR-396: Add basic client to talk with API (part 1)

server/data/incidentReportingApi.ts, server/data/incidentReportingApiUtils.ts, server/routes/index.ts
Added methods and types to get reports with details (e.g. staff/prisoners involvement, questions, etc...)
**NOTE**: the API has distinct "types" for Questions/Responses and historical ones - possibly because they're baked by different DB tables on the JPA side of things - but their format is the same so the UI types are the same.
This is simpler. We can always introduce more types when/if these will ever diverge.
Types for "enums" values like staff/prisoner roles, prisoner involvement outcome or correction request reasons are still defined as string (although we have a type alias) as they will likely change - we may also _possibly_/maybe move these into the UI from the API. But for now aliases to string will do.
=> IR-396: Incident Reporting client methods to get reports with details

cypress.config.ts, integration_tests/e2e/health.cy.ts, integration_tests/mockApis/offenderSearchApi.ts, server/config.ts, server/data/offenderSearchApi.ts, server/routes/index.ts, server/services/healthCheck.ts, server/utils/nunjucksSetup.ts, server/utils/utils.test.ts, server/utils/utils.ts, server/views/pages/report.njk
Use Prisoner Search API's `POST /prisoner-search/prisoner-numbers` endpoint to get the names of the prisoners involved in a report.
Prisoner full names are displayed using the `nameOfPerson` nunjucks filter.
This was copied over from Non-associations with a bunch of related filters.
=> IR-365: Show prisoners' names

server/@types/index.d.ts, server/data/incidentReportingApi.test.ts, server/data/incidentReportingApi.ts, server/data/incidentReportingApiUtils.test.ts, server/data/incidentReportingApiUtils.ts, server/data/offenderSearchApi.test.ts, server/data/testData/incidentReporting.ts, server/data/testData/offenderSearch.ts, server/data/testData/paginatedResponses.ts, server/data/testData/thrownErrors.ts, server/sanitisedError.ts, server/utils/format.test.ts, server/utils/format.ts, server/utils/utils.test.ts, server/utils/utils.ts
We only have debugging routes/views at present and little of their code is likely to remain in future.
The incident-reporting API client, however, will still be around so ought to have some tests!
As part of this, there is some test event and report generation being added – these will prove necessary for mocking out the API.
=> IR-404: Test API clients

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
Use alertSeverity provided by CP team.
These would send alerts to the
`#incident-reporting-service-dev` Slack channel.
=> IR-421: Send alerts to our dev channel

local.env, server/config.ts
The “production” flag does not have a clear meaning, but enforced TLS. When the app is run fully in docker locally, it meant that TLS was required and therefore authentication could not function.
=> IR-431: Add variable to allow removing the TLS requirement in “production” mode

integration_tests/mockApis/frontendComponents.ts, integration_tests/mockApis/wiremock.ts, server/data/frontendComponentsClient.ts, server/data/testData/frontendComponents.ts, server/middleware/frontendComponents.test.ts, server/middleware/frontendComponents.ts, server/middleware/populatePrisoner.test.ts, server/middleware/populateReport.test.ts
`/header` & `/footer` endpoints are deprecated and [`/components`](https://frontend-components.hmpps.service.justice.gov.uk/api-docs/#/default/get_components) should be used instead
=> IR-527: Use non-deprecated endpoint to load DPS micro-frontend components

server/utils/utils.test.ts, server/utils/utils.ts
Internally, the date is converted into UTC so effectively 1 day was subtracted when using the returned value with `format.isoDate(…)`:
`03/10/2024` is parsed into `2024-10-02T23:00:00.000Z` (in Europe/London) and truncation results in `"2024-10-02"`
=> IR-68: Fix date parsing for BST time

server/@types/express/index.d.ts, server/@types/hmpo-form-wizard/application-extensions.d.ts, server/@types/hmpo-form-wizard/index.d.ts, server/@types/hmpo-model/index.d.ts, server/controllers/base/formInitialStep.ts, server/data/incidentTypeConfiguration/formWizard.ts, server/data/incidentTypeConfiguration/wip/generateFieldsWithConditionals.ts, server/data/incidentTypeConfiguration/wip/generateStepsWithConditionals.ts, server/errorHandler.test.ts, server/errorHandler.ts, server/helpers/field/flattenConditionalFields.test.ts, server/helpers/field/flattenConditionalFields.ts, server/helpers/field/reduceDependentFields.test.ts, server/helpers/field/reduceDependentFields.ts, server/helpers/field/renderConditionalFields.test.ts, server/routes/addPrisoner/fields.ts, server/routes/addPrisoner/steps.ts, server/routes/changeIncident/fields.ts, server/routes/changeIncident/steps.ts, server/routes/createIncident/fields.ts, server/routes/createIncident/steps.ts, server/routes/generic/fields.ts, server/routes/generic/steps.ts, server/routes/questions/router.ts, server/utils/backUrl.ts
…with clear separation between library and custom additional properties. It’s better to use declaration merging.
Types copied from `hmpps-locations-inside-prison` & `hmpps-strengths-based-needs-assessments-ui` include a lot of application-specific properties that are not applicable to incident reporting and associated code does not exist in this repository.
This PR is easiest to review by first looking at changes made to application code: nearly none! Some types have been tightened up, other declarations now specify types rather than using type assertions (i.e. types are checked rather than assumed).
In future, we will need to tidy up custom properties hanging off form wizard types:
- reuse existing functionality (back links & conditional fields are already supported by the library)
- …
=> IR-534: Recreate HMPO form wizard types afresh

server/utils/govukFrontend.test.ts, server/utils/govukFrontend.ts, server/utils/nunjucksSetup.test.ts, server/utils/nunjucksSetup.ts
The `govukCheckedItemsConditional` filter is used to add conditional html to GDS radio or checkbox components.
```typescript
res.render('template', {
items: [
{ text: 'A', value: 'a' },
{ text: 'B', value: 'b' },
],
})
```
```nunjucks
{% set conditional %}
{{ govukInput({
name: 'comment',
id: 'comment',
label: { text: 'Comment' }
}) }}
{% endset %}
{{ govukCheckboxes({
id: 'sample',
name: 'sample',
fieldset: { legend: { text: 'Sample' } },
items: items | govukCheckedItemsConditional({
value: 'b',
html: conditional
})
}) }}
```
---
The `govukCheckedItemsDivider` filter adds a divider to GOVUK checkbox or radio component items.
```nunjucks
{{ govukCheckboxes({
id: 'sample',
name: 'sample',
fieldset: { legend: { text: 'Sample' } },
items: items | govukCheckedItemsDivider()
}) }}
```
---
The …
=> IR-68: Nunjucks utilities to help keep presentation logic within template files

server/@types/hmpo-form-wizard/index.d.ts, server/controllers/index.test.ts, server/controllers/index.ts, server/controllers/wip/questionsController.ts, server/views/pages/wip/questions/questionPage.njk, server/views/partials/errorSummary.njk, server/views/partials/formErrorSummary.njk
Add an abstract form wizard controller that adds human-readable messages to errors if they're missing. The new “questions” wizard now extends it.
=> IR-548: Simple error message handling for form wizard pages

server/@types/hmpo-form-wizard/index.d.ts, server/controllers/base/formInitialStep.ts, server/controllers/index.ts
… so that one can opt into proper form values type checking.
Notable from this PR is that no existing controllers _needed_ to be changed! Example of opting into better typing:
```typescript
interface Form {
field1: string
field2: string
field3: string[]
}
type Step1 = 'field1'
class Step1Controller extends BaseController<Form, Step1> {}
type Step2 = 'field2' | 'field3'
class Step2Controller extends BaseController<Form, Step2> {
validate(
req: FormWizard.Request<Pick<Form, Step2>>,
res: Express.Response,
next: Express.NextFunction,
): void {
super.validate(req, res, next)
// ↓ req.form.values.field2 is accessible
if (problemWith(req.form.values.field2)) {
next(…)
}
// req.form.values.field1 // ← inaccessible field!
}
}
```
=> IR-531: Add generic parameters to form wizard controllers

server/@types/hmpo-form-wizard/index.d.ts
Errors are actually always passed around controller methods associated to fields, as partial records
=> IR-531: Improve error types for form wizard lib

server/@types/hmpo-form-wizard/index.d.ts, server/data/incidentTypeConfiguration/formWizard.test.ts, server/data/incidentTypeConfiguration/formWizard.ts, server/views/pages/wip/questions/questionPage.njk
If multiple answers lead to the same next question they'll share the same next step condition.
For example:
- Q1 has 3 answers
- Answer 1 and 3 leads to Q2
- But Answer 2 leads to Q3
In this case Answer 1 and 3 would have the same next step condition.
For questions with a lot of answers leading to the same next question this means a much more compact steps object.
Also improved accuracy of some of the related Form Wizard types.
=> IR-519: Improve next step conditions

integration_tests/e2e/createReport.cy.ts, integration_tests/index.d.ts, integration_tests/mockApis/auth.ts, integration_tests/mockApis/incidentReportingApi.ts, integration_tests/mockApis/manageUsersApi.ts, integration_tests/mockApis/wiremock.ts, integration_tests/pages/createReport/details.ts, integration_tests/pages/createReport/type.ts, integration_tests/pages/formWizard.ts, integration_tests/pages/page.ts, integration_tests/support/commands.ts, server/@types/hmpo-form-wizard/index.d.ts, server/@types/hmpo-form-wizard/index.test.ts, server/data/incidentReportingApi.test.ts, server/data/incidentReportingApi.ts, server/data/incidentReportingApiUtils.test.ts, server/data/testData/incidentReporting.ts, server/data/testData/manageUsers.ts, server/routes/reports/createReport.test.ts, server/routes/reports/createReport.ts, server/routes/testutils/appSetup.ts, server/services/userService.test.ts, server/utils/format.test.ts, server/utils/format.ts, server/utils/nunjucksSetup.ts, server/views/macros/renderDateField.njk, server/views/pages/createReport/details.njk, server/views/partials/formWizardLayout.njk
- add basic wiremock stubs for incident reporting endpoints
- add integration tests for creating a report successfully
- as usual, there are DST / timezone bugs 😩 – node likes to convert dates into UTC. this would be fine if our api was using timezone-aware dates, but since it uses naive dates during BST it was seeing all date/times with 1 hour subtracted
- improve test data so that prison-api and manage-users apis are aware of the same mock users
=> IR-548: Integration tests for basic create report journey

server/@types/hmpo-form-wizard/index.d.ts, server/@types/hmpo-form-wizard/index.test.ts, server/controllers/addPrisoner/addPrisoner.ts, server/controllers/base/formInitialStep.ts, server/controllers/generic/genericPage1.ts, server/controllers/generic/genericPage2.ts, server/controllers/generic/genericPage3.ts, server/controllers/generic/involvedParties.ts, server/controllers/generic/policeInformed.ts, server/controllers/index.test.ts, server/controllers/index.ts, server/data/incidentTypeConfiguration/formWizard.test.ts, server/data/incidentTypeConfiguration/formWizard.ts, server/middleware/setUpAuthentication.ts, server/routes/forms/get.ts, server/routes/forms/post.ts, server/routes/reports/createReport.ts, server/routes/reports/detailsController.ts, server/routes/reports/updateReportDetails.ts
This is good practice according to eslint because
```typescript
import type Express from 'express'
// and
import type { Express } from 'express'
```
refer to different things. It’s best that we use the package name `express` as the default import name instead.
This “problem” was spotted when [testing migrating to eslint 9](https://github.com/ministryofjustice/hmpps-incident-reporting/pull/255)
=> IR-68: Import default express namespace types using a name that is not itself exported as well

integration_tests/e2e/createReport.cy.ts, server/data/incidentReportingApi.test.ts, server/data/incidentReportingApi.ts, server/data/testData/incidentReporting.ts, server/routes/dashboard.ts, server/routes/reports/createReport.test.ts, server/routes/reports/createReport.ts, server/views/pages/dashboard.njk, server/views/pages/debug/eventDetails.njk, server/views/pages/debug/reportDetails.njk
…to match api changes with respect to creating, retrieving and updating their models
Depends on [api#206](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/206)
=> IR-631: Rename `prisonId` fields to `location` in reports and events

server/controllers/addPrisoner/addPrisoner.ts, server/controllers/wip/questionsController.ts, server/data/incidentTypeConfiguration/formWizard.ts, server/data/testData/FINDS.ts, server/middleware/populateReport.test.ts, server/middleware/populateReport.ts, server/reportConfiguration/types/index.ts, server/routes/index.ts, server/routes/questions/router.ts, server/routes/questionsRoute.test.ts, server/views/pages/wip/questions/questionPage.njk
Report questions page now display a report's responses to questions.
- moved questions page from `/:reportType/questions` to `/reports/:id/questions` as it now loads a report and shows the questions based on a given report's type
- the form's values are set from each of the questions' responses, unless a value is already set on the form (e.g. because user submitted a different value)
- matching between responses and fields values is done by answers' code: the `response` field of the answer's response is the "code" of the answer (e.g. `'YES'`, not an answer ID, nor the answer's label, e.g. `'Yes'`)
- values have to be set differently depending on whether the question allows multiple choices (`string[]` for checkboxes)  or a single response (`string` for radio buttons).
- each response can …
=> IR-576: View report answers

server/controllers/wip/questionsController.ts, server/data/incidentReportingApi.ts, server/routes/questions/router.test.ts, server/routes/questionsRoute.test.ts
Ability to save answers to a report's questions.
This is using the recently added [`PUT /incident-reports/{reportId}/questions`](https://incident-reporting-api-dev.hmpps.service.justice.gov.uk/swagger-ui/index.html#/Questions%20and%20responses%20forming%20an%20incident%20report/addOrUpdateQuestionsWithResponses) endpoint so it would either save the answer if this is the first time it was submitted or it would update the answer if a previous answer record was present.
=> IR-621: Ability to save answers to questions

server/controllers/wip/questionsController.ts, server/middleware/populateReport.ts, server/routes/questions/router.ts
Don't look up conditional fields as questions. This is to avoid unnecessary false errors in the logs.
When questions/answers are submitted the submitted values' keys are fields names. However these field names can be either a question ID or a conditional field name (e.g. comment/date).
This change only look up question IDs in the report config.
NOTE: This does not change what we post to the API. Conditional fields values are still submitted when the question's answers require date/comment.
=> Questions controller reduce errors

server/views/pages/wip/questions/questionPage.njk
It is still easily possible to show the debug info by temporarily toggle the `if` statement condition in local environment when needed.
We can remove later on, but for now it's useful to be able to quickly have a look at these information.
=> Hide debug info in questions page

server/controllers/wip/questionsController.ts, server/data/incidentTypeConfiguration/types.ts, server/routes/viewReport.ts
When displaying questions/answers in the report view strip any possible `QID-` prefix that may still be present in the data returned by the API.
Long term, once all the data will no longer have
these prefixes (e.g. all environment have been re-migrated) we can remove this simple logic. Although for codes without this prefix this is a no-op.
=> Report view: Questions case: Account for `QID-` prefix

server/routes/questions/router.test.ts, server/views/pages/wip/questions/questionPage.njk
Looping through the fields in `option.fields` sometimes results in the questions in a group being deplayed in an order which is different from the one in the config.
This makes sure the fields are rendered in the same order as they appear in the step/config.
=> IR-721: Ensure questions are rendered in order

server/controllers/addPrisoner/addPrisoner.ts, server/data/incidentReportingApi.test.ts, server/data/incidentReportingApi.ts, server/data/testData/incidentReporting.ts
Adapting to changes in [api#237](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/237)
=> IR-722: Require report involvements to have names

server/routes/viewReport.test.ts, server/routes/viewReport.ts, server/views/pages/debug/reportDetails.njk
Summary of changes made in this PR:
- Text within status tag now the "user friendly" version
- Added missing date to summary title 
- Reformatted detailed within prisoners involved to include comments
- Same done for staff involved
- Add responses button removed. 
- "Change" link in question responses now takes you to start of questions with answers filled.
- Any dates showing in question responses are now formatted
- The following changes to correction requests section:
- 1. First column shows who made the request
- 2. Details now show Description of change in first line, followed by Date and time of when it was submitted on the second.
=> Changes made to view report page as per IR-733 with corresponding changes made to some unit tests

server/data/testData/prisonApi.ts, server/middleware/permissions.test.ts, server/middleware/permissions.ts, server/routes/dashboard.test.ts, server/routes/reports/createReport.ts, server/routes/reports/permissions.ts, server/views/pages/dashboard.njk, server/views/pages/index.njk
Improves on #304 to take user’ active caseloads into account when creating reports. This is necessary since there is no way to choose a prison when creating a report and active caseload must be assumed.
=> IR-687: Permissions checks for creating reports

assets/scss/components/_header-bar.scss
The sass compiler issues a deprecation warnings about ordering of nested declarations but only in the fallback header component. Reordering plain properties first appeases it, but doesn’t change the actual effect on layout. (Users never see this fallback header anyway)
=> IR-68: SCSS tweak

server/views/partials/formWizardLayout.njk
i buggered up the size when i changed all the links to not indicate visited state
=> IR-68: Fix cancel link on form wizard pages – the font size was wrong

server/routes/dashboard/tableColumns.ts
Changed background column name to match filters and query. Mismatch was causing error when sorting
=> Establishment column sort bug fix

package-lock.json, package.json, server/middleware/setUpStaticResources.ts
Continues on from #342 to add missing route to GOV.UK assets for DPR pages and remove seemingly-unnecessary dependency and jQuery route
=> IR-790: DPR assets

integration_tests/mockApis/manageUsersApi.ts, server/data/manageUsersApiClient.test.ts, server/data/manageUsersApiClient.ts
Uses the [`GET /prisonusers/search` endpoint] to search for NOMIS users.
This endpoint was chosen instead of other (similar) [`GET /users/search` endpoint](https://manage-users-api.hmpps.service.justice.gov.uk/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/user-search-controller/searchForUsersInMultipleSourceSystems) because response
contains active caseload of users (when present) which is something designs suggest
is needed.
The query string is matched against first/last name, username or email address.
Client needs the `MAINTAIN_ACCESS_ROLES_ADMIN` role (currently anyway) to be able to search all users.
[`GET /prisonusers/search` endpoint]: https://manage-users-api.hmpps.service.justice.gov.uk/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/user-search-control …
=> IR-801: Added `searchUsers()` method to Manage Users API client

integration_tests/mockApis/manageUsersApi.ts, server/controllers/involvements/summary.ts, server/data/incidentTypeConfiguration/questionProgress.test.ts, server/data/incidentTypeConfiguration/questionProgress.ts, server/data/incidentTypeConfiguration/utils.ts, server/routes/reports/questions/controller.ts, server/services/questionsToDelete.test.ts, server/services/questionsToDelete.ts
Key lock incident highlighted a few problems related to inactive question & response configuration. This was not always filtered out meaning that
- some valid responses were accidentally being deleted
- the incorrect next question/page was being chosen
Also, clearing form wizard session when questions are saved successfully in the hope of preventing form wizards interfering with each other.
=> IR-740: Fix question/response configuration traversal

server/routes/reports/prisoners/search/controller.ts, server/routes/reports/staff/search/controller.ts
While it wasn’t preventing any normal user interactions, the search pages remembered the last thing you searched for
=> IR-950: Clear prisoner & staff search session if successfully rendered

integration_tests/e2e/changeType.cy.ts, integration_tests/e2e/createCompletedReport.cy.ts, integration_tests/e2e/createMinimalDraftReport.cy.ts, integration_tests/e2e/dashboard.cy.ts, integration_tests/e2e/viewReport.cy.ts, integration_tests/pages/reports/type.ts, server/middleware/populateReportConfiguration.test.ts, server/middleware/populateReportConfiguration.ts, server/middleware/redirectOnReportStatus.test.ts, server/middleware/redirectOnReportStatus.ts, server/routes/index.ts, server/routes/reports/details/changeType.test.ts, server/routes/reports/details/changeType.ts, server/routes/reports/details/updateReportDetails.test.ts, server/routes/reports/viewReport.test.ts, server/views/pages/reports/confirm-type-change.njk, server/views/pages/reports/view/_details.njk
Depends on [api#196](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/196): API handles archiving questions and clearing prisoner involvements.
=> IR-954: Allow changing a report’s type

assets/scss/dpr.scss, esbuild/assets.config.js, server/views/partials/dprLayout.njk
Continues on from #398:
• it appears that DPR SCSS bundle can be built if additional undocumented load paths are provided to the sass plugin
=> IR-958: Bundle DPR stylesheets into one file

scripts/validateConfig.ts, server/data/incidentTypeConfiguration/validation.test.ts, server/data/incidentTypeConfiguration/validation.ts, server/reportConfiguration/types/index.ts
While we run validations on import from NOMIS, there was still the potential that a change to these could lead to invalid configurations.
This is to run these validation with the rest of the tests.
Notable changes:
- I've made `getAllIncidentTypeConfigurations()` synchronous (see commit message for reasoning)
- I've added a validation for the questions/answers IDs to check that they don't include hyphens as this could lead to issues, see [prior discussion](https://github.com/ministryofjustice/hmpps-incident-reporting/pull/403#discussion_r2028814884).
=> IR-970: Run incident type config validations as part of the test suite

server/middleware/permissions.test.ts, server/middleware/permissions.ts
This would allow presenting a helpful message to use NOMIS in place of a missing action button
Current rules:
```
Access to the service
should be denied to missing user
should be denied to user without roles
should be granted to reporting officer
should be granted to data warden
should be granted to HQ view-only user
Viewing a report
in Leeds
should be denied to missing user
should be denied to user without roles or Leeds caseload
should be denied to user without roles but with Leeds caseload
should be denied to reporting officer without Leeds caseload
should be granted to reporting officer with Leeds caseload
should be granted to reporting officer with Leeds caseload and PECS role
should be denied to data warden without Leeds caseload
should be granted to data warden with Leeds caseload …
```
=> Add more “allowed to do X in NOMIS only” permissions checks

server/@types/express/index.d.ts, server/controllers/base.test.ts, server/controllers/base.ts, server/controllers/involvements/remove.ts, server/controllers/involvements/summary.ts, server/errorHandler.test.ts, server/routes/debug.ts, server/routes/index.ts, server/routes/reports/details/changeType.ts, server/routes/reports/details/createReport.ts, server/routes/reports/details/updateReportDetails.ts, server/routes/reports/prisoners/involvement/add.ts, server/routes/reports/prisoners/involvement/edit.ts, server/routes/reports/prisoners/remove/index.ts, server/routes/reports/prisoners/search/index.ts, server/routes/reports/prisoners/summary/index.ts, server/routes/reports/questions/controller.ts, server/routes/reports/questions/index.ts, server/routes/reports/staff/involvement/add.ts, server/routes/reports/staff/involvement/edit.ts, server/routes/reports/staff/involvement/manual/add.ts, server/routes/reports/staff/remove/index.ts, server/routes/reports/staff/search/index.ts, server/routes/reports/staff/summary/index.ts
Form wizard sessions were being cleared slightly too early. The root controller class’ success handler [adds a history step to the journey model](https://github.com/HMPO/hmpo-form-wizard/blob/f9ad4df65d500eea2128e6773f09980e17e53d3b/lib/controller/index.js#L360) _after_ we cleared the session. It’s presence in the session later meant those same controller could not tell where to send the user.
=> IR-973: Clear form wizard session more strategically

integration_tests/pages/reports/type.ts, server/routes/reports/details/changeType.test.ts, server/views/pages/reports/confirm-type-change.njk
=> IR-1026: Make heading and warning text consistent when users change incident type

server/data/constants.ts, server/data/testData/users.ts, server/middleware/permissions/rulesClass.test.ts, server/middleware/permissions/rulesClass.ts, server/routes/dashboard/index.test.ts, server/routes/dashboard/index.ts, server/routes/index.test.ts, server/routes/reports/details/addDescription.test.ts, server/routes/reports/details/changeType.test.ts, server/routes/reports/details/createReport.test.ts, server/routes/reports/details/updateIncidentDateAndTime.test.ts, server/routes/reports/details/updateReportDetails.test.ts, server/routes/reports/history/status.test.ts, server/routes/reports/history/type.test.ts, server/routes/reports/prisoners/involvement/add.test.ts, server/routes/reports/prisoners/involvement/edit.test.ts, server/routes/reports/prisoners/remove/index.test.ts, server/routes/reports/prisoners/search/index.test.ts, server/routes/reports/prisoners/summary/index.test.ts, server/routes/reports/questions/index.test.ts, server/routes/reports/staff/involvement/add.test.ts, server/routes/reports/staff/involvement/edit.test.ts, server/routes/reports/staff/involvement/manual/add.test.ts, server/routes/reports/staff/remove/index.test.ts, server/routes/reports/staff/search/index.test.ts, server/routes/reports/staff/summary/index.test.ts, server/routes/reports/viewReport.test.ts, server/routes/testutils/appSetup.ts
This abstraction makes it easier to reason about the logic of each permission check and to compare against designs and requirements.
Previously, several checks required the presence of `roleReadWrite` _and the absence_ of `roleApproveReject`. That’s because `roleReadWrite` flagged a reporting officer and `roleApproveReject` flagged a data warden… but a user cannot be both!
Now this is just `isReportingOfficer` because the most powerful role determines the user type and all allowable actions stem from there.
---
Also, mock user variables have been renamed to follow these user type groupings.
=> IR-1047: Categorise users into types before determining permissions

integration_tests/e2e/createCompletedReport.cy.ts, integration_tests/e2e/respondToQuestions.cy.ts, integration_tests/e2e/viewReport.cy.ts, server/data/incidentReportingApi.test.ts, server/data/incidentReportingApi.ts, server/data/incidentTypeConfiguration/questionProgress.test.ts, server/data/testData/incidentReporting.ts, server/data/testData/incidentReportingJest.ts, server/routes/reports/history/type.test.ts, server/routes/reports/questions/controller.ts, server/routes/reports/questions/index.test.ts, server/routes/reports/viewReport.test.ts
Controller handling question responses now parses in response code/ID into the api call. 
Along with this, some types in Incident reporting API needed to be altered. This had a knock on effect to many tests.
=> Added response code to api calls for question responses

server/utils/azureAppInsights.ts, server/utils/azureAppinsights.test.ts
…and ignore boring HTTP request paths. Copied from non-associations app.
=> IR-68: Add more context to Azure Application Insights logging

helm_deploy/hmpps-incident-reporting/values.yaml, helm_deploy/values-prod.yaml
Currently there is a mismatch between the API's start/stop schedule and the UI start/stop schedule and 'retry-dlq' CronJob schedule (this is specified in UTC time)
This changes the UI schedule so that:
- time is now specified in UTC like in other places and also we don't have to worry about summer time difference
- API will start at 6:49am, UI will start later at 7:00am
- UI will stop before at at 9:50pm, API will stop later at 9:58pm
**NOTE**: _Ideally_ this should be applied around the same time as [this sibling API PR](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/361/files).
=> Tweaked start/stop schedule

server/routes/index.ts, server/routes/reports/lookupReference.test.ts, server/routes/reports/lookupReference.ts
… so that “this is a duplicate of  report X” comments can link to the report without first looking up it’s ID
=> IR-1083: Allow linking to a report by incident number (ie. reference)

integration_tests/e2e/createCompletedReport.cy.ts, integration_tests/e2e/involvements/prisoners/add.cy.ts, integration_tests/e2e/involvements/prisoners/involvements.cy.ts, integration_tests/e2e/involvements/prisoners/remove.cy.ts, integration_tests/e2e/involvements/prisoners/search.cy.ts, integration_tests/e2e/involvements/staff/involvements.cy.ts, integration_tests/mockApis/prisonApi.ts, server/data/prisonApi.ts, server/routes/reports/actions/actionReport.test.ts, server/routes/reports/prisoners/involvement/add.test.ts, server/routes/reports/prisoners/involvement/add.ts, server/routes/reports/prisoners/remove/controller.ts, server/routes/reports/prisoners/remove/index.test.ts, server/routes/reports/viewReport.ts, server/services/reportTitle.test.ts, server/services/reportTitle.ts
Report titles are determined by prisoner involvements so need to be regenerated when they are added or removed.
Since at that point, the change in prisoner involvement is more important to save successfully, the update of title is allowed to fail. This is because when a report is submitted, the title is once again regenerated; at which point it isn’t allowed to fail.
=> IR-1054: Update report titles when prisoner involvements change

integration_tests/e2e/changeType.cy.ts, integration_tests/e2e/involvements/prisoners/edit.cy.ts, server/routes/reports/details/changeType.test.ts, server/routes/reports/details/changeType.ts, server/routes/reports/prisoners/involvement/edit.test.ts, server/routes/reports/prisoners/involvement/edit.ts
Adds to changes in #496:
- when type is changed, the title should definitely be regenerated
- when a prisoner involvement is updated, technically the title remains the same but seems prudent to keep the code more consistent with respect to prisoner involvements
=> IR-1054: Regenerate report title when type changes

server/reportConfiguration/constants/statuses.ts, server/reportConfiguration/constants/workLists.ts, server/routes/reports/actions/actionReport.test.ts, server/routes/reports/actions/reopen/index.test.ts, server/routes/reports/actions/requestRemoval/index.test.ts, server/routes/reports/details/changeType.test.ts
Reverts ministryofjustice/hmpps-incident-reporting#515
Depends ministryofjustice/hmpps-incident-reporting-api#378
=> Undo IR-1040: Remove “Post-incident update” status

assets/scss/page/_dashboard.scss, server/views/pages/dashboard/index.njk
Removes the bottom space in the expanded status details cell in the dashboard table. 
As per ticket IR-1176
[IR-1176]: https://dsdmoj.atlassian.net/browse/IR-1176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added new css for status cell in dashboard table to remove bottom margin

integration_tests/e2e/journeys/actionPecsReport.cy.ts, integration_tests/e2e/journeys/actionPrisonReport.cy.ts, integration_tests/e2e/journeys/actionReport.ts, integration_tests/e2e/journeys/actionSubmittedReport.cy.ts, integration_tests/e2e/journeys/createCompleteReport.cy.ts, integration_tests/e2e/journeys/createCompletedReport.cy.ts, integration_tests/e2e/journeys/recallReport.cy.ts, server/middleware/correctPecsReportStatus.test.ts, server/middleware/correctPecsReportStatus.ts, server/middleware/permissions/statusTransitions.ts, server/middleware/populatePrisoner.ts, server/middleware/populateReport.ts, server/middleware/populateReportConfiguration.ts, server/middleware/populateStaffMember.ts, server/middleware/redirectOnReportStatus.ts, server/middleware/updateActiveAgencies.ts, server/routes/reports/actions/actionPecsReport.test.ts, server/routes/reports/viewReport.test.ts, server/routes/reports/viewReport.ts
NB: the diffs are much more manageable if looking commit-by-commit, ignoring whitespace
- test PECS report actions
- add middleware that corrects unexpected PECS report statuses (when viewed by data wardens)
=> IR-1167: PECS reports

assets/scss/page/_dashboard.scss, server/@types/express/index.d.ts, server/data/incidentReportingApi.ts, server/data/testData/incidentReporting.ts, server/middleware/permissions/userActions.ts, server/routes/dashboard/index.ts, server/views/pages/dashboard/statusFilters.njk
Adding new filter to enable DWs to filter for removal requests. 
Work done:
- Updated API call and associated types to filter for removal requests via `lastUserAction` parameter
- Updated basic report type to include new variable `lastUserAction`
- Added filter with validation on to the dashboard. 
No tests have been added for this yet. 
No unit tests have been broken, integration tests are now broken.
=> IR-1215 removals filter
