Dockerfile, package.json
=> Move to Debian 12 / bookworm

.circleci/config.yml, package-lock.json, package.json
=> IR-68: Complete upgrade to Node 20.12

helm_deploy/values-prod.yaml
Ref: [prison-api#2156](https://github.com/ministryofjustice/prison-api/pull/2156)
=> IR-68: Migrate to `prison-api` in Cloud Platform

.circleci/config.yml, .eslintrc.json, .gitignore, Dockerfile, assets/js/application.js, assets/scss/application.scss, esbuild/app.config.js, esbuild/assets.config.js, esbuild/esbuild.config.js, esbuild/index.d.ts, helm_deploy/hmpps-incident-reporting/values.yaml, package-lock.json, package.json, server/app.ts, server/data/hmppsAuditClient.test.ts, server/middleware/setUpStaticResources.ts, server/routes/testutils/appSetup.ts, server/utils/nunjucksSetup.ts, server/views/partials/layout.njk, tsconfig.json
Ref:
- [hmpps-ip-allowlists#21](https://github.com/ministryofjustice/hmpps-ip-allowlists/pull/21)
- [hmpps-template-typescript#384](https://github.com/ministryofjustice/hmpps-template-typescript/pull/384)
- [hmpps-template-typescript#375](https://github.com/ministryofjustice/hmpps-template-typescript/pull/375)
- [hmpps-template-typescript#377](https://github.com/ministryofjustice/hmpps-template-typescript/pull/377)
- [hmpps-template-typescript#389](https://github.com/ministryofjustice/hmpps-template-typescript/pull/389)
=> IR-68: Sync changes from templates

cypress.config.ts, integration_tests/e2e/health.cy.ts, integration_tests/mockApis/prisonApi.ts, integration_tests/tsconfig.json, server/@types/express/index.d.ts, server/app.ts, server/config.ts, server/data/prisonApi.ts, server/middleware/setApis.ts, server/middleware/setSystemToken.ts, server/routes/debug.ts, server/routes/testutils/appSetup.ts, server/services/healthCheck.ts, server/views/pages/debug/incidentDetails.njk, server/views/pages/debug/reportDetails.njk
Show prison names instead of their IDs.
Also refactored things a little to move some of the common set-up logic related to APIs in a couple of small middleware.
=> IR-376: Show prison names

server/data/incidentReportingApi.ts
Ref [api#169](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/169)
=> IR-425: Add staff & prisoner involvement filters to report-listing method

docker-compose.yml, wiremock/__files/prisoners-lookup.json, wiremock/mappings/prisoners-lookup.json
Depends on [api#173](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/173)
=> IR-431 Add prisoner lookup mock data and mappings

package-lock.json, package.json, server/app.ts, server/routes/addPrisoner/index.ts, server/routes/changeIncident/index.ts, server/routes/createIncident/index.ts, server/routes/generic/index.ts
…because this is already handled by other middleware.
Relates to #167 and #181
=> IR-68: Remove form wizard's session timeout check

scripts/importDpsConstants.ts, scripts/listDownloadLinks.ts, scripts/updateNomisIncidentTypeConfigurations.ts, scripts/utils.ts, scripts/validateConfig.ts, server/reportConfiguration/types/index.ts
Previously, validation only happened on import of NOMIS types. It will be useful to run it against our future types and any manual modifications should they ever be made.
=> IR-505: Add script to validate existing report config

scripts/listDownloadLinks.ts
calling `./scripts/listDownloadLinks.ts <env> --verbose` with verbose flag will list download links for known NOMIS types
=> IR-496: List known NOMIS types for constants downloads

server/data/incidentTypeConfiguration/formWizard.ts, server/routes/questions/router.ts
- fix flowing to next page not working
- fix validation not showing
- explain why we need `checkSession`/`csrf` set to `false`
=> Steps tweaks

server/@types/express/index.d.ts, server/data/testData/frontendComponents.ts, server/middleware/frontendComponents.test.ts, server/middleware/frontendComponents.ts, server/routes/testutils/appSetup.ts
…when loading frontend components because current prison (active case load) will be needed in many places in this website
=> IR-531: Store user case load information

server/@types/hmpo-form-wizard/index.d.ts, server/data/incidentTypeConfiguration/formWizard.test.ts, server/data/incidentTypeConfiguration/formWizard.ts, server/views/components/wip/renderField/_conditionalHtml.njk, server/views/components/wip/renderField/renderField.njk
This is starting to grow so I think it's a good idea to merge this batch of improvements:
- fix for checkboxes not going to next page
- retain user selection on error
- validate date fields with `ukDate`
- don't generate steps/fields for inactive questions/answers as it's wasteful
- added tests for `generateSteps()`/`generateFields()`
- tweaks to FormWizard types
=> IR-519: Various improvements to questions steps/fields

server/data/incidentTypeConfiguration/formWizard.ts
Map also has a `has()` method to check if a given
key is in it.
=> Replaced `get() === undefined` with `!has()`

README.md
Depends on:
- [nomis-user-roles-api#303](https://github.com/ministryofjustice/nomis-user-roles-api/pull/303)
- [hmpps-auth#1811](https://github.com/ministryofjustice/hmpps-auth/pull/1811)
- [api#200](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/200)
=> IR-573: Update test users and their roles for local testing

server/reportConfiguration/types/DAMAGE.ts
To reflect deactivation in NOMIS, See:
https://mojdt.slack.com/archives/C060K95M5MJ/p1731322757968019
=> Deactivate DAMAGE

integration_tests/e2e/createReport.cy.ts, server/reportConfiguration/constants/types.ts
=> Deactivate `DAMAGE` type

server/data/incidentReportingApi.ts, server/data/testData/incidentReporting.ts, server/reportConfiguration/constants/errorCodes.ts
Depends on [api#207](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/207)
=> IR-574: Indicate which system last modified a report: NOMIS or DPS

server/controllers/index.test.ts, server/forms/index.test.ts, server/forms/prisonerSearchForm.test.ts, server/middleware/permissions.test.ts, server/routes/forms/get.test.ts, server/routes/forms/post.test.ts, server/routes/index.test.ts, server/routes/reports/createReport.test.ts, server/routes/reports/updateReportDetails.test.ts, server/utils/utils.test.ts
`toBeTruthy()` matches too much potentially
=> IR-68: Use stricter test assertions

server/data/incidentReportingApi.ts, server/data/testData/incidentReporting.ts
Ref: [api#262](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/262)
=> IR-761: Update IRS api types to handle staff & prisoner involvement flags

server/routes/reports/viewReport.test.ts, server/routes/reports/viewReport.ts, server/views/pages/debug/reportDetails.njk
=> IR-740: Hide question/response change links from users who cannot edit reports

server/reportConfiguration/constants/statusMappings.ts, server/routes/dashboard/dashboard.test.ts, server/routes/dashboard/dashboard.ts, server/utils/utils.test.ts, server/utils/utils.ts
Fixed bug where 'to do' status reappeared on RO view. Added validation and error messages for location and status/work list
=> Dashboard tweaks

server/routes/dashboard/dashboard.ts
Updated logic on RO default to not reinstate default when sorting table or moving to another page of table
=> Fixed RO filter/table bug

server/data/incidentTypeConfiguration/validation.test.ts, server/data/incidentTypeConfiguration/validation.ts
All answers [to multiple choices questions] should lead to the same next question. This is because otherwise a user may choose answers in such a way that it is ambiguous to know which question to show next.
Throughout the codebase we assume that when a question allow multiple choices they all lead to the same next question (and just take the next question ID from the 1st answer as it shouldn't matter).
Note that thix validation only considers active questions and active answers as inactive ones don't matter.
Result of validation are in ticket: IR-793
=> IR-769: Validation on multiple choices questions

server/controllers/addPrisoner/prisonerSearch.ts, server/controllers/wip/questionsController.ts, server/middleware/populateReport.test.ts, server/middleware/populateReport.ts, server/routes/debug.ts, server/routes/index.ts, server/routes/reports/questions.ts, server/routes/reports/updateReportDetails.ts, server/views/pages/addPrisoner/prisonerSearch.njk
…so that it’s clearer what it points to
=> IR-798: Rename report route parameter name

assets/scss/local.scss, server/@types/express/index.d.ts, server/controllers/prisonerSummary/prisonerSummary.ts, server/controllers/removePrisoner/removePrisoner.ts, server/controllers/removeStaff/removeStaff.ts, server/controllers/staffSummary/staffSummary.ts, server/routes/reports/prisoners/involvement/add.test.ts, server/routes/reports/prisoners/involvement/add.ts, server/routes/reports/prisoners/involvement/controller.ts, server/routes/reports/prisoners/involvement/edit.test.ts, server/routes/reports/prisoners/involvement/edit.ts, server/views/partials/notificationBanner.njk
accidentally missed in #358 – there is a situation where you try to add or edit a prisoner involvement but there are no roles available
=> IR-820: Show error when there are no prisoner roles available

package-lock.json, package.json, server/data/incidentReportingApi.test.ts, server/data/incidentReportingApi.ts, server/routes/dpr/index.ts, server/routes/index.ts, server/views/pages/index.njk, server/views/pages/managementReporting/index.njk
=> IR-824: Add reporting tile on the home page and provide a list of available reports (POC)

server/data/restClient.ts
…without which typescript 5.8 complains
=> IR-68: Use stricter typing in REST client

server/@types/moj-frontend/index.d.ts, server/utils/nunjucksSetup.ts
…where they started exporting the filters as part of the package [moj-frontend#1256](https://github.com/ministryofjustice/moj-frontend/pull/1256)
Related to #377
=> IR-68: Update app for MoJ frontend v4

integration_tests/e2e/dashboard.cy.ts, integration_tests/pages/dashboard.ts, server/data/incidentReportingApi.ts, server/routes/dashboard/index.test.ts, server/routes/dashboard/index.ts, server/views/pages/dashboard.njk
Depends on [api#303](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/303)
=> Filter dashboard by type *families*

server/reportConfiguration/constants/typeFamilies.ts, server/reportConfiguration/constants/typeHints.ts, server/reportConfiguration/constants/types.test.ts, server/reportConfiguration/constants/types.ts, server/routes/reports/history/type.test.ts
Related [api#305](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/305)
=> IR-785: Simplify damage incident type description

integration_tests/e2e/changeType.cy.ts, server/routes/reports/details/changeType.test.ts, server/routes/reports/details/changeType.ts
…like in the create journey so they do not have to click into each individual section given that most info was deleted
=> IR-972: Changing type leads users through all questions

server/middleware/setUpStaticResources.ts, server/views/partials/dprLayout.njk
…now that they use default paths and bundle all necessary components
=> IR-68: Fix DPR static assets loading

server/data/incidentReportingApi.test.ts, server/data/incidentReportingApi.ts, server/data/incidentReportingApiUtils.ts, server/data/testData/incidentReporting.ts
Depends on [api#329](https://github.com/ministryofjustice/hmpps-incident-reporting-api/pull/329)
=> IR-1000: Update CRUD endpoints for IRS api

server/reportConfiguration/constants/statusMappings.ts, server/reportConfiguration/constants/statuses.ts, server/routes/dashboard/index.test.ts
New statuses need to be mapped into groups for reporting officers
Ref #441
=> IR-1041: Status mappings

integration_tests/e2e/viewReport.cy.ts, server/views/pages/reports/view/index.njk
implements designs from IR-912 but it’s possible that IR-913 may change content in a future iteration
=> IR-914: Insert breadcrumb above report page to dashboard

server/reportConfiguration/constants/statuses.ts, server/reportConfiguration/constants/workLists.ts, server/routes/reports/actions/actionReport.test.ts, server/routes/reports/actions/reopen/index.test.ts, server/routes/reports/actions/requestRemoval/index.test.ts, server/routes/reports/details/changeType.test.ts
Depends on ministryofjustice/hmpps-incident-reporting-api#381
=> IR-1040: Re-remove “Post-incident update” status

integration_tests/e2e/dashboard.cy.ts, integration_tests/e2e/home.cy.ts, integration_tests/pages/dashboard.ts, integration_tests/pages/home.ts, server/middleware/permissions/rulesClass.test.ts, server/middleware/permissions/rulesClass.ts, server/middleware/setUpPecsRegions.test.ts, server/middleware/setUpPecsRegions.ts, server/routes/dashboard/index.test.ts, server/routes/dashboard/index.ts, server/routes/index.test.ts, server/routes/index.ts, server/views/pages/dashboard.njk, server/views/pages/index.njk
- Adds some entry points to create a PECS report: but the actual journey does NOT exist yet. PECS reports cannot be created yet.
- Adds additional filtering options to the dashboard based on location
=> IR-908: Initial PECS work

integration_tests/e2e/journeys/createCompletedReport.cy.ts, integration_tests/e2e/journeys/submitToDoReport.cy.ts, server/middleware/permissions/statusTransitions.ts
Couple of small content changes to success banners following confusion raised by Amanda in [IR-1193] 
[IR-1193]: https://dsdmoj.atlassian.net/browse/IR-1193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Confirmation messages

server/views/pages/prisoners/search.njk, server/views/pages/reports/view/_prisoners.njk
Adds the link to take user to the prisoner profile page within DPS to the name within results in the prisoner search when attempting to add a prisoner to a report.
Also made the same profile link on the "view report" page open the profile in another tab.
=> IR-1212 prisoner profile links
